[2023-02-03T06:52:30.076+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [queued]>
[2023-02-03T06:52:30.085+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [queued]>
[2023-02-03T06:52:30.085+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T06:52:30.086+0200] {taskinstance.py:1280} INFO - Starting attempt 5 of 8
[2023-02-03T06:52:30.086+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T06:52:30.094+0200] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-15 10:29:20.696392+00:00
[2023-02-03T06:52:30.100+0200] {standard_task_runner.py:55} INFO - Started process 50238 to run task
[2023-02-03T06:52:30.104+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'manual__2023-01-15T10:29:20.696392+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmpvxhrb3g5']
[2023-02-03T06:52:30.105+0200] {standard_task_runner.py:83} INFO - Job 578: Subtask etl_pipeline
[2023-02-03T06:52:30.172+0200] {task_command.py:388} INFO - Running <TaskInstance: railway_v02.etl_pipeline manual__2023-01-15T10:29:20.696392+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-02-03T06:52:30.231+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-15T10:29:20.696392+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-15T10:29:20.696392+00:00
[2023-02-03T06:52:46.055+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 107, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-02-03T06:52:46.063+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230115T102920, start_date=20230203T045230, end_date=20230203T045246
[2023-02-03T06:52:46.074+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 578 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 50238)
[2023-02-03T06:52:46.083+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-03T06:52:46.152+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
