[2023-01-15T12:33:14.459+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-15T12:33:14.473+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-15T12:33:14.473+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:33:14.473+0200] {taskinstance.py:1284} INFO - Starting attempt 6 of 6
[2023-01-15T12:33:14.474+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:33:14.485+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-02 00:00:00+00:00
[2023-01-15T12:33:14.495+0200] {standard_task_runner.py:55} INFO - Started process 48687 to run task
[2023-01-15T12:33:14.501+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '528', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmpplw_06fi']
[2023-01-15T12:33:14.504+0200] {standard_task_runner.py:83} INFO - Job 528: Subtask etl_pipeline
[2023-01-15T12:33:14.573+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-02T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:33:14.643+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-15T12:34:11.325+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 113, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-01-15T12:34:11.451+0200] {taskinstance.py:1322} INFO - Marking task as FAILED. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230102T000000, start_date=20230115T103314, end_date=20230115T103411
[2023-01-15T12:34:12.331+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 528 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 48687)
[2023-01-15T12:34:12.388+0200] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-15T12:34:12.883+0200] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
