[2023-01-15T12:20:24.055+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-15T12:20:24.122+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-02T00:00:00+00:00 [queued]>
[2023-01-15T12:20:24.123+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:20:24.124+0200] {taskinstance.py:1284} INFO - Starting attempt 4 of 6
[2023-01-15T12:20:24.125+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:20:24.184+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-02 00:00:00+00:00
[2023-01-15T12:20:24.213+0200] {standard_task_runner.py:55} INFO - Started process 40928 to run task
[2023-01-15T12:20:24.228+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'scheduled__2023-01-02T00:00:00+00:00', '--job-id', '491', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmplkhh056b']
[2023-01-15T12:20:24.239+0200] {standard_task_runner.py:83} INFO - Job 491: Subtask etl_pipeline
[2023-01-15T12:20:24.577+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-02T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:20:24.797+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-02T00:00:00+00:00
[2023-01-15T12:21:45.562+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 113, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-01-15T12:21:45.886+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230102T000000, start_date=20230115T102024, end_date=20230115T102145
[2023-01-15T12:21:46.481+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 491 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 40928)
[2023-01-15T12:21:46.503+0200] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-15T12:21:46.740+0200] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
