[2023-02-03T07:02:26.548+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-02-03T04:36:43.127403+00:00 [queued]>
[2023-02-03T07:02:26.557+0200] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline manual__2023-02-03T04:36:43.127403+00:00 [queued]>
[2023-02-03T07:02:26.557+0200] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T07:02:26.558+0200] {taskinstance.py:1280} INFO - Starting attempt 3 of 6
[2023-02-03T07:02:26.558+0200] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-02-03T07:02:26.567+0200] {taskinstance.py:1300} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-02-03 04:36:43.127403+00:00
[2023-02-03T07:02:26.573+0200] {standard_task_runner.py:55} INFO - Started process 52316 to run task
[2023-02-03T07:02:26.577+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'manual__2023-02-03T04:36:43.127403+00:00', '--job-id', '597', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmpyci9sgts']
[2023-02-03T07:02:26.580+0200] {standard_task_runner.py:83} INFO - Job 597: Subtask etl_pipeline
[2023-02-03T07:02:26.648+0200] {task_command.py:388} INFO - Running <TaskInstance: railway_v02.etl_pipeline manual__2023-02-03T04:36:43.127403+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-02-03T07:02:26.711+0200] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-02-03T04:36:43.127403+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-03T04:36:43.127403+00:00
[2023-02-03T07:02:44.645+0200] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 107, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-02-03T07:02:44.664+0200] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230203T043643, start_date=20230203T050226, end_date=20230203T050244
[2023-02-03T07:02:44.679+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 597 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 52316)
[2023-02-03T07:02:44.711+0200] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-02-03T07:02:44.738+0200] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
