[2023-01-15T10:11:21.694+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2022-12-11T00:00:00+00:00 [queued]>
[2023-01-15T10:11:21.820+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2022-12-11T00:00:00+00:00 [queued]>
[2023-01-15T10:11:21.823+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T10:11:21.834+0200] {taskinstance.py:1284} INFO - Starting attempt 3 of 6
[2023-01-15T10:11:21.835+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T10:11:21.990+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2022-12-11 00:00:00+00:00
[2023-01-15T10:11:22.066+0200] {standard_task_runner.py:55} INFO - Started process 13736 to run task
[2023-01-15T10:11:22.115+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'scheduled__2022-12-11T00:00:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmp3uzqylg9']
[2023-01-15T10:11:22.137+0200] {standard_task_runner.py:83} INFO - Job 331: Subtask etl_pipeline
[2023-01-15T10:11:23.336+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline scheduled__2022-12-11T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T10:11:24.599+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-11T00:00:00+00:00
[2023-01-15T10:16:55.640+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 43, in etl_pipeline
    df_dict = {k: spark.createDataFrame(json.loads(v)) for (k,v) in res_dict.items()}
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 43, in <dictcomp>
    df_dict = {k: spark.createDataFrame(json.loads(v)) for (k,v) in res_dict.items()}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2023-01-15T10:16:55.871+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20221211T000000, start_date=20230115T081121, end_date=20230115T081655
[2023-01-15T10:16:56.014+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 331 for task etl_pipeline (Expecting value: line 1 column 1 (char 0); 13736)
