[2023-01-15T12:20:01.081+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2022-12-07T00:00:00+00:00 [queued]>
[2023-01-15T12:20:01.102+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2022-12-07T00:00:00+00:00 [queued]>
[2023-01-15T12:20:01.103+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:20:01.103+0200] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2023-01-15T12:20:01.104+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:20:01.119+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2022-12-07 00:00:00+00:00
[2023-01-15T12:20:01.134+0200] {standard_task_runner.py:55} INFO - Started process 40737 to run task
[2023-01-15T12:20:01.142+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'scheduled__2022-12-07T00:00:00+00:00', '--job-id', '489', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmp9swfhw6j']
[2023-01-15T12:20:01.145+0200] {standard_task_runner.py:83} INFO - Job 489: Subtask etl_pipeline
[2023-01-15T12:20:01.244+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline scheduled__2022-12-07T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:20:01.345+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-07T00:00:00+00:00
[2023-01-15T12:20:58.704+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 113, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-01-15T12:20:58.832+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20221207T000000, start_date=20230115T102001, end_date=20230115T102058
[2023-01-15T12:20:59.668+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 489 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 40737)
[2023-01-15T12:20:59.706+0200] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-15T12:21:00.021+0200] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
