[2023-01-15T12:26:46.353+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-15T12:26:46.377+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-03T00:00:00+00:00 [queued]>
[2023-01-15T12:26:46.379+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:26:46.380+0200] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2023-01-15T12:26:46.380+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:26:46.400+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-03 00:00:00+00:00
[2023-01-15T12:26:46.417+0200] {standard_task_runner.py:55} INFO - Started process 43796 to run task
[2023-01-15T12:26:46.428+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'scheduled__2023-01-03T00:00:00+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmp5hx7fb1u']
[2023-01-15T12:26:46.434+0200] {standard_task_runner.py:83} INFO - Job 515: Subtask etl_pipeline
[2023-01-15T12:26:46.538+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-03T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:26:46.650+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-03T00:00:00+00:00
[2023-01-15T12:28:09.253+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 113, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-01-15T12:28:09.532+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230103T000000, start_date=20230115T102646, end_date=20230115T102809
[2023-01-15T12:28:09.623+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 515 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 43796)
