[2023-01-15T12:27:00.844+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-15T12:27:00.922+0200] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2023-01-15T12:27:00.924+0200] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:27:00.924+0200] {taskinstance.py:1284} INFO - Starting attempt 5 of 6
[2023-01-15T12:27:00.925+0200] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-15T12:27:01.009+0200] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): etl_pipeline> on 2023-01-01 00:00:00+00:00
[2023-01-15T12:27:01.037+0200] {standard_task_runner.py:55} INFO - Started process 43934 to run task
[2023-01-15T12:27:01.051+0200] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'railway_v02', 'etl_pipeline', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '518', '--raw', '--subdir', 'DAGS_FOLDER/fetching_api.py', '--cfg-path', '/var/folders/qr/k2__dmk5697g2jyd7w2tpyt80000gn/T/tmpplx9r_6z']
[2023-01-15T12:27:01.056+0200] {standard_task_runner.py:83} INFO - Job 518: Subtask etl_pipeline
[2023-01-15T12:27:01.322+0200] {task_command.py:389} INFO - Running <TaskInstance: railway_v02.etl_pipeline scheduled__2023-01-01T00:00:00+00:00 [running]> on host nhanchaus-macbook-air.local
[2023-01-15T12:27:01.656+0200] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Nhan_Chau
AIRFLOW_CTX_DAG_ID=railway_v02
AIRFLOW_CTX_TASK_ID=etl_pipeline
AIRFLOW_CTX_EXECUTION_DATE=2023-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=5
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-01T00:00:00+00:00
[2023-01-15T12:28:22.300+0200] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/nhanchau/gitRepo/Raiway_with_AIrflow/dags/fetching_api.py", line 113, in etl_pipeline
    SparkSession.stop()
TypeError: SparkSession.stop() missing 1 required positional argument: 'self'
[2023-01-15T12:28:22.337+0200] {taskinstance.py:1322} INFO - Marking task as UP_FOR_RETRY. dag_id=railway_v02, task_id=etl_pipeline, execution_date=20230101T000000, start_date=20230115T102700, end_date=20230115T102822
[2023-01-15T12:28:22.373+0200] {standard_task_runner.py:100} ERROR - Failed to execute job 518 for task etl_pipeline (SparkSession.stop() missing 1 required positional argument: 'self'; 43934)
